services:
  postgres:
    image: 'postgres:latest'
    container_name: db
    environment:
      - 'POSTGRES_DB=payments'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '15432:5432'

  rest-server:
    image: 'ezycollect-demo:0.0.1-SNAPSHOT'
    depends_on:
      - postgres
    container_name: rest
    environment:
      - 'SPRING_PROFILES_ACTIVE=dev'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/payments'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=secret'

    ports:
      - '8080:8080'
